version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000

    #    for dollar signs in secret key add another dollar sign to it otherwise the docker-compose sees it as an error.
    environment:
      - SECRET_KEY=ln2)sw+w)gki9d+v%b$$yl+f7y*s^y15!-ft*&z*$$_5vd)gh)xd
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:9.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  postgres_data: