# Generated by Django 2.2.7 on 2020-04-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default=1, upload_to='covers/'),
            preserve_default=False,
        ),
    ]
